- src/KeyConnector/Dockerfile
- src/KeyConnector/Services/CryptoService.cs
- src/KeyConnector/Services/RsaHealthCheckService.cs
- src/KeyConnector/Startup.cs
* add a health check endpoint at `/health`. Currently this will just check that the RSA key can be successfully accessed and loaded. It returns a simple "Healthy" or "Unhealthy" result, but it should be enough to prompt the user to check logs. This endpoint is used by Docker to report on the container health as well, so the result will show in `docker container ls`.
* only save a new encKey in memory _after_ saving to database, as a preventative measure in case we have issues with saving it
We discussed making the application terminate if the health check fails on start, but I didn't think that was necessary. With these changes, there is better reporting back to the user, and Key Connector simply won't work if the RSA key cannot be loaded. (Although I can still add this in if required.)
> [EC-177] Add health checks and fast-fail

- src/KeyConnector/Services/CryptoService.cs
Follow-on from https://github.com/bitwarden/key-connector/pull/16.
* update variable name, we need to encrypt `newSymmetricKey`, not `_symmetricKey` (which is still null)
* if the RSA encryption fails, it can return null and then you get a cryptic B64 error. Instead, add null check and throw a more helpful error.
> [EC-178] Fix RSA encrypt for newSymmetricKey, add null check

- src/KeyConnector/appsettings.Development.json
Update the Key Connector default development settings to match the ports that we use for self-hosted development.
Key Connector only works for self-hosted instances, so there didn't seem any point in creating a separate launch profile like we have for server.
> Update internal Uris to match self-hosted dev settings

- .github/workflows/release.yml
This PR disables DCT in the `release` workflow since we never set it up fully.
> Disable DCT for Release Workflow

- .github/workflows/release.yml
The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.
> Update deprecated Azure Key Vault in workflows

- src/KeyConnector/Exceptions/InvalidKeyTypeException.cs
- src/KeyConnector/KeyConnectorSettings.cs
- src/KeyConnector/Services/AwsKmsRsaKeyService.cs
- src/KeyConnector/Services/GoogleCloudKmsRsaKeyService.cs
- src/KeyConnector/Startup.cs
Key Connector uses an RSA key as a Key Encryption Key, encrypting a symmetric key for all the data at rest ([envelope encryption](https://cloud.ibm.com/docs/key-protect?topic=key-protect-envelope-encryption#envelope-encryption-overview)).
We previously never specified an `EncryptionAlgorithm` while encrypting/decrypting using AWS. This meant that the KMS client was using the default `SYMMETRIC_DEFAULT` and expecting users to use a symmetric key.
This fixes the AWS key service to use RSA encryption instead, and adds a setting to allow older users to continue using their symmetric key.
> [PM-1348] Fix AWS expecting symmetric key

- .github/CODEOWNERS
This PR updates the `CODEOWNERS` file so that DevOps can approve PRs created by the `Version Bump` workflow.
> Update CODEOWNERS for version bump

- src/KeyConnector/Dockerfile
- src/KeyConnector/entrypoint.sh
This PR changes the `Dockerfile` and `entrypoint.sh` script to use the logic/layout from `v2023.5.0`, but retains some updates like using .NET 6 as a base image.
> Fix Docker image

- .github/renovate.json
Ignores the .NET SDK with Renovate since we want to keep it at `.100`.
> Ignore .NET SDK updates with Renovate

- src/KeyConnector/Dockerfile
This PR applies fixes for most of the Checkmarkx findings for the `Dockerfile`.  We cannot currently at this time apply the `USER` instruction unless we move the `ca-certificates` feature to a volume mount.
> Docker - Apply fixes for Checkmarkx findings

- .github/workflows/release.yml
This PR fixes the deprecated `set-output` syntax.
> Release Workflow - Remove set-output

- src/KeyConnector/KeyConnector.csproj
- src/KeyConnector/Services/HashicorpVaultCertificateProviderService.cs
In https://github.com/bitwarden/key-connector/pull/95, we updated `VaultSharp` from `1.7.0` to `1.13.0.1`.  Doing so broke the retrieval of certificates from HashiCorp Vault for our Key Connector customers.
After adding debugging logging, we were unable to quickly address the problem.  This PR reverts back to the known working dependency version, and we will need to address the breaking change when we have more time without customers being affected.
In adding (and removing) the debug logging, I added a `ILogger` to the certificate retrieval service, and I elected to keep it in this PR in order to provide for any future logging work, and also to explicitly log an error if there were an issue retrieving the certificate.
> [PM-5619] Revert VaultSharp version update to fix HashiCorp cert errors

- src/KeyConnector/Services/AwsKmsRsaKeyService.cs
We have a customer who would like to use their Amazon instance metadata for authentication instead of an Id and secret that is configured with environment variables.
To support this, [their documentation](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) specifies that we should construct the client without passing in the Id and secret.
In this change, we check if **both** the Id and secret are empty, and if so assume that the user wishes to use instance metadata.
> [PM-6116] Update AWS key service to handle authentication with instance metadata

- dev/setup_secrets_windows.ps1
Updated windows setup script to target local user's certificate store to avoid access issues in the future.
This means a user shouldn't need to be in an elevated terminal/prompt/cmd etc. to create and export the certificate.
> Fixing setup script for Windows

- dev/.gitignore
- src/KeyConnector/HostedServices/TransferToHostedService.cs
- src/KeyConnector/KeyConnectorSettings.cs
- src/KeyConnector/Properties/launchSettings.json
- src/KeyConnector/Repositories/EntityFramework/UserKeyRepository.cs
- src/KeyConnector/Repositories/IUserKeyRepository.cs
- src/KeyConnector/Repositories/JsonFile/UserKeyRepository.cs
- src/KeyConnector/Repositories/Mongo/UserKeyRepository.cs
- src/KeyConnector/ServiceCollectionExtensions.cs
- src/KeyConnector/Startup.cs
- src/KeyConnector/appsettings.json
This PR adds a hosted service that will be run on startup to transfer user keys from one database and/or RSA key configuration to another.
The service will only run once and then locks itself from running again by placing a lockfile on disk. If you clear the lockfile, it will run again the next time Key Connector starts.
This example shows moving from one JSON database and RSA key to another. The database and RSA configuration could be any of the configuration values that we support.
```json
{
"keyConnectorSettings:database:provider": "json",
"keyConnectorSettings:database:jsonFilePath": "/etc/bitwarden/database.json",
"keyConnectorSettings:rsaKey:provider": "certificate",
"keyConnectorSettings:certificate:provider": "filesystem",
"keyConnectorSettings:certificate:filesystemPath": …
```
> [PM-7171] Tool to transfer user keys to a new service

- .github/workflows/build.yml
- .github/workflows/clean-up-rc-branch.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/version-bump.yml
- Directory.Build.props
- bitwarden-key-connector.sln
- src/KeyConnector/KeyConnector.csproj
- test/KeyConnector.Tests/KeyConnector.Tests.csproj
- test/KeyConnector.Tests/ThrowawayTests.cs
Adds a test project so future unit tests can be written. Since this is now the second project in the solution, there's also a move to use `Directory.Build.props` with the versioning centralized there and workflow updates to match.
> [PM-9310] Add test project and necessary workflows to use it, with centralized versioning

- src/KeyConnector/ServiceCollectionExtensions.cs
- src/KeyConnector/Services/Pkcs11/IPkcs11InteropFactory.cs
- src/KeyConnector/Services/Pkcs11/Pkcs11InteropFactory.cs
- src/KeyConnector/Services/Pkcs11/Pkcs11RsaKeyService.cs
- test/KeyConnector.Tests/KeyConnector.Tests.csproj
- test/KeyConnector.Tests/Services/Pkcs11RsaKeyServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-9310
Fixes an issue with using `Pkcs11Interop` on linux. 
In order to add tests I had to refactor out the library so wasn't tightly coupled to the service. I'm interested if reviewers believe these tests are too focused on the implementation vs just the behavior.
> add tests and refactor Pkcs11RsaKeyService

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/test.yml
- .github/workflows/version-bump.yml
This PR updates the Release workflow to use the `dev` tag for releasing.  The rest of the workflows were updated with linting suggestions.
> BRE-278 - Apply Docker image tag fix for Release workflow

- .github/workflows/publish.yml
- .github/workflows/release.yml
Split `key-connector` GitHub Release from Deploy/Publish.
> BRE-141 Refactor Release workflow to split deploy/publish steps

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/VULN-130
Signs container images built off `main` with [Cosign](https://github.com/sigstore/cosign). This uses Sigstore's in-house certificate authority with short-lived keys that are all self-managed with the tool, which will also utilize GitHub's provided OIDC entity. As part of an effort to increase transparency of what we build as an open source company, these signatures are also sent to [Rekor](https://search.sigstore.dev/) -- users of our images are then free to verify the images against that log.
- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) …
> Sign main branch container builds with cosign
