- .github/workflows/build.yml
- .github/workflows/release.yml
- src/KeyConnector/KeyConnector.csproj
Adds the following.
* Build pipeline that will run CLOC, creates an artifact from source, and builds docker images.
* Release pipeline that tags docker then creates docker and github releases.
* Adds in `<Version>` tag to `KeyConnector.csproj` and sets it to `1.0.0` as a base for incrementing release versions.
> Adding build and release pipelines

- .github/workflows/build.yml
Somehow this was missed when applying github's PR recommendations.
> Removed unneeded job step that somehow got missed in previous PR

- src/KeyConnector/Properties/launchSettings.json
Prevents automatically opening a browser window on lanch.
> Disable automatically launching browser

- .github/workflows/version-bump.yml
Adds github workflow for version bumping the .csproj file.
> Added version-bump workflow

- .github/workflows/version-bump.yml
Updates the `Version Bump` action to the latest version.
- **.github/workflows/version-bump.yml:** Updates the `version-bump` action to the latest hash.
> Update Version Bump action to latest

- .github/workflows/release.yml
Adds a dry run release option to test release workflow logic without actually deploying anything.
> Added dry run logic to release workflow

- .github/workflows/build.yml
- Updates old actions to their newest version
> Updated actions

- .github/workflows/build.yml
- .github/workflows/release.yml
Enable docker image signing for key-connector in release workflow.
> Enable DCT in release workflow

- .github/workflows/release.yml
Update to newest version of `release-version-check` action
- **.github/workflows/release.yml:** Update hash
> Update the version of bitwarden/gh-actions/release-version-check

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/version-bump.yml
- .github/workflows/workflow-linter.yml
- Update all workflow files to latest actions
> [DEVOPS-1414] - UPDATE: all workflows

- .github/CODEOWNERS
```
```
This PR adds @bitwarden/dept-devops to the `CODEOWNERS` file for all Docker related files.
- **.github/CODEOWNERS:** Add DevOps as owners for Docker related files.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
> Add DevOps to CODEOWNERS for files related to Docker

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/version-bump.yml
- .github/workflows/workflow-linter.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR builds upon @joseph-flinn's work [here](https://github.com/bitwarden/key-connector/pull/89), and streamlines both the `build` and `release` workflows to resemble our other repositories as closely as possible.
Successful run [here](https://github.com/bitwarden/key-connector/actions/runs/7050079669).
> Update build and release workflows

- src/KeyConnector/KeyConnector.csproj
updated various libraries in the `.csproj` to address compatibility issues.
worked with @notnamed to verify function of docker container on a dev instances.
> [PM-5067] Dependency issues

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/version-bump.yml
```
```
Update workflows to point to `main` and update the other use cases of the `master` branch
- **.github/workflows/*:** Change all relevant references of internal `master` branches to `main`
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
> Point workflows to `main`

- .github/CODEOWNERS
-   🎂 Other
This PR updates the `CODEOWNERS` file by adding a line for `.github/renovate.json` so that multiple teams can edit the Renovate config.
-   **.github/CODEOWNERS:** Add line for `.github/renovate.json`.
-   Contributor guidelines followed
-   All formatters and local linters executed and passed
-   Written new unit and / or integration tests where applicable
-   Used internationalization (i18n) for all UI strings
-   CI builds passed
-   Communicated to DevOps any deployment requirements
-   Updated any necessary documentation or informed the documentation team
-   👍 (`:+1:`) or similar for great changes
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
-   ❓ (`:question:`) for questions
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
> Make renovate.json updatable by multiple teams

- .github/workflows/version-bump.yml
```
```
This PR fixes an error where `xmllint` is not found.
* **.github/workflows/version-bump.yml:** Add in step to install `xmllint`. Fix `while` loop logic.
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
> Version Bump workflow - Add step for installing xmllint

- .github/workflows/release.yml
[Card](https://bitwarden.atlassian.net/browse/DEVOPS-1803)
> [DEVOPS-1803] - Update Failure Job

- .github/workflows/release.yml
[Card](https://bitwarden.atlassian.net/browse/DEVOPS-1803)
> [DEVOPS-1803] - Fix if check

- .github/workflows/version-bump.yml
```
- [] New feature development
```
Report upcoming release to Slack using the generate version bump by the workflow.
Related PR: https://github.com/bitwarden/gh-actions/pull/281
* **.github/workflows/version-bump.yml:** Add step to report upcoming release
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
> BRE-40 Add step to report upcoming release version to Slack

- .github/workflows/version-bump.yml
```
```
Add a new parameter to whether to send a notification for upcoming releases, which must be disabled by default.
Related PR: https://github.com/bitwarden/devops/pull/2329
* **.github/workflows/version-bump.yml:** Add new input
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
> BRE-87 Add Slack notification enable feature and check in version-bump workflow

- .github/workflows/scan.yml
[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288) - Deploy scanning workflow organization wide
[PM-7288]: https://bitwarden.atlassian.net/browse/PM-7288
> Include actions to support Checkmarx and Sonar scanning workflow

- .github/workflows/build.yml
Adds container scanning with Grype.
> Add container scanning

- .github/workflows/test.yml
Adds conditionals to check for secret existence in workflows so they don't fail on forks.
> Check for secrets before using them

- .github/workflows/build.yml
- .github/workflows/scan.yml
- .github/workflows/test.yml
> Don't test or scan on nonexistent RCs

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/test.yml
- .github/workflows/version-bump.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372)
> [BRE-372] - Clean up document start

- .github/workflows/build.yml
- .github/workflows/publish.yml
- README.md
- [BRE-648](https://bitwarden.atlassian.net/browse/BRE-648?atlOrigin=eyJpIjoiZTIxODAzZGEyNWNmNDVmNmFmYmMwZjYwYTdmNTBmMjAiLCJwIjoiaiJ9)
This PR updates where we store our container images from Docker Hub to ghcr.io.
- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team
- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for …
> BRE-648 - Update Docker registry to GHCR

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/version-bump.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Updating to use Azure Key Vault Secrets in place of GitHub secrets.
All GitHub secrets have been migrated to the repository's respective Key Vault.
Azure Service Principals have been updated to use Managed Identities with OIDC.
- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team
- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ …
> [BRE-831] migrate secrets AKV

- .github/CODEOWNERS
[BRE-1040](https://bitwarden.atlassian.net/browse/BRE-1040)
Add AppSec team as owner of Dockerfile, and Dockerfile related, files.
- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team
- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
> BRE-1040 Dockerfile shared ownership

- .github/workflows/build.yml
- .github/workflows/cleanup-container-images.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/test.yml
- .github/workflows/version-bump.yml
- [BRE-1190](https://bitwarden.atlassian.net/browse/BRE-1190?atlOrigin=eyJpIjoiNmU1NDA4ZGZjMzNkNDE4NjljMjkzNjEzNTg3MzFkZmMiLCJwIjoiaiJ9)
This PR updates the workflows to use GHCR instead of Azure ACR for container images. There are a list of miscellaneous fixes below.
- Added `concurrency` to prevent multiple runs of the same branch at the same time.
- Updated all runners to `ubuntu-24.04`.
- Removed test output.
- Added `retention-days` to uploaded artifact to cut down on storage usage.
- Updated the `build-docker` job to use GHCR.
- Add extra logic for the image tag generation step in order to make sure the tags are valid.
- This workflow has been added to clean up any container images in GHCR that are from deleted branches.
- Update `curl` command to point to the `key-connector` …
> BRE-1190 - Update workflows to use GHCR instead of Azure ACR
